spring.application.name=Chat AI
server.port=8081

spring.ai.vertex.ai.gemini.project-id=${PROJECT_ID}
spring.ai.vertex.ai.gemini.location=us-east4
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash